### ISSUE TITLE
Update to 2.3.0p14.cre fails

### ISSUE THREAD

**Issue by peterge-misoft** [inettgmbh/checkmk-proxmox_backup_server#8]
```
2024-09-03 09:57:54 - Updating site 'misoft' from version 2.3.0p13.cre to 2.3.0p14.cre...

Creating temporary filesystem /omd/sites/misoft/tmp...OK
ATTENTION
  Some steps may take a long time depending on your installation.
  Please be patient.

Cleanup precompiled host and folder files
Verifying Checkmk configuration...
Failed to load plug-in /omd/sites/misoft/local/share/check_mk/web/plugins/wato/proxmox_bs.py: No module named 'cmk.gui.cee'
Traceback (most recent call last):
  File "/omd/sites/misoft/lib/python3/cmk/gui/utils/__init__.py", line 67, in load_web_plugins
    exec(
  File "/omd/sites/misoft/local/share/check_mk/web/plugins/wato/proxmox_bs.py", line 14, in <module>
    from cmk.gui.cee.plugins.wato.agent_bakery.rulespecs.utils import (
ModuleNotFoundError: No module named 'cmk.gui.cee'
Failed to load plug-in /omd/sites/misoft/local/share/check_mk/web/plugins/wato/proxmox_bs.py: No module named 'cmk.gui.cee'
Traceback (most recent call last):
  File "/omd/sites/misoft/lib/python3/cmk/gui/utils/__init__.py", line 67, in load_web_plugins
    exec(
  File "/omd/sites/misoft/local/share/check_mk/web/plugins/wato/proxmox_bs.py", line 14, in <module>
    from cmk.gui.cee.plugins.wato.agent_bakery.rulespecs.utils import (
ModuleNotFoundError: No module named 'cmk.gui.cee'
 01/06 Legacy check plug-ins...
 02/06 Rulesets...
 03/06 UI extensions...
Failed to load plug-in /omd/sites/misoft/local/share/check_mk/web/plugins/wato/proxmox_bs.py: No module named 'cmk.gui.cee'
Traceback (most recent call last):
  File "/omd/sites/misoft/lib/python3/cmk/gui/utils/__init__.py", line 67, in load_web_plugins
    exec(
  File "/omd/sites/misoft/local/share/check_mk/web/plugins/wato/proxmox_bs.py", line 14, in <module>
    from cmk.gui.cee.plugins.wato.agent_bakery.rulespecs.utils import (
ModuleNotFoundError: No module named 'cmk.gui.cee'
Incompatible file '/omd/sites/misoft/local/share/check_mk/web/plugins/wato/proxmox_bs.py' of extension package 'proxmox_bs 0.3
.9'
Error: No module named 'cmk.gui.cee'


Traceback (most recent call last):
  File "/omd/sites/misoft/lib/python3/cmk/update_config/main.py", line 100, in main_check_config
    check_config(logger, conflict)
  File "/omd/sites/misoft/lib/python3/cmk/update_config/main.py", line 241, in check_config
    pre_action(logger, conflict_mode)
  File "/omd/sites/misoft/lib/python3/cmk/update_config/plugins/pre_actions/ui_extensions.py", line 60, in __call__
    if disable_incomp_mkp(
       ^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/misoft/lib/python3/cmk/update_config/plugins/pre_actions/utils.py", line 115, in disable_incomp_mkp
    and _request_user_input_on_incompatible_file().lower() in USER_INPUT_DISABLE
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/misoft/lib/python3/cmk/update_config/plugins/pre_actions/utils.py", line 134, in _request_user_input_on_inc
ompatible_file
    return prompt(
           ^^^^^^^
  File "/omd/sites/misoft/lib/python3/cmk/update_config/plugins/pre_actions/utils.py", line 44, in prompt
    tcflush(sys.stdin, TCIFLUSH)
termios.error: (25, 'Inappropriate ioctl for device')

Update aborted with Error: (25, 'Inappropriate ioctl for device').
Your site has not been modified.
The update can be retried after the error has been fixed.
```

I just tried to install 2.3.0p14.cre, which did fail bc of the proxmox_bs plugin. Updating works fine after running `mkp disable proxmox_bs`.

**Comment by peterge-misoft** [comment]
https://forum.checkmk.com/t/proxmox-backup-plugin-not-working-after-upgrade-to-2-3-0p14/49381

**Comment by nedjitef** [comment]
Thanks, we're on it.
Which version of CMK are you using? raw, cee or cme

You could check if the [latest release 0.4.20](https://github.com/inettgmbh/checkmk-proxmox_backup_server/releases/tag/0.4.20) works for you.

**Comment by peterge-misoft** [comment]
> Thanks, we're on it. Which version of CMK are you using? raw, cee or cme
> 
> You could check if the [latest release](https://github.com/inettgmbh/checkmk-proxmox_backup_server/releases/latest) works for you.

I am not sure what I am doing wrong, but I cant test it.
I updated the [script](https://github.com/inettgmbh/checkmk-proxmox_backup_server/blob/main/cmk_addons_plugins/proxmox_bs/agent_based/proxmox_bs.py), but it shows this error:
```
root@pbsbn:/usr/lib/check_mk_agent/plugins# chmod +x proxmox_bs.py 
root@pbsbn:/usr/lib/check_mk_agent/plugins# ls -l
total 8
-rwxr-xr-x 1 root root 7791 Apr 28 07:18 proxmox_bs.py
root@pbsbn:/usr/lib/check_mk_agent/plugins# python3 proxmox_bs.py 
Traceback (most recent call last):
  File "/usr/lib/check_mk_agent/plugins/proxmox_bs.py", line 9, in <module>
    from cmk.agent_based.v2 import (
ModuleNotFoundError: No module named 'cmk'
```

The extension is installed, but shows up as inactive:
```
OMD[misoft]:~$ mkp list
Name       Version Title                      Author                                                                    Req. Version Until Version Files State                          
---------- ------- -------------------------- ------------------------------------------------------------------------- ------------ ------------- ----- -------------------------------
proxmox_bs 0.4.21  Proxmox Backup Server      Felix Driessler <fdriessler@inett.de>                                     2.3.0b6      None          5     Enabled (inactive on this site)
redfish    2.3.38  Redfish Restful API Checks Andreas Doehler (andreas.doehler@bechtle.com / andreas.doehler@gmail.com) 2.3.0b6      2.3.99        28    Disabled                       
OMD[misoft]:~$ mkp update-active
[proxmox_bs 0.4.21]: Installing
[proxmox_bs 0.4.21]: Not installed: File conflict: /omd/sites/misoft/local/share/check_mk/agents/plugins/proxmox_bs (already existing)
OMD[misoft]:~$ rm /omd/sites/misoft/local/share/check_mk/agents/plugins/proxmox_bs
OMD[misoft]:~$ mkp update-active
[proxmox_bs 0.4.21]: Installing
Traceback (most recent call last):
  File "/omd/sites/misoft/bin/mkp", line 83, in <module>
    cli.main(
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 813, in main
    args.handler(
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 84, in wrapped
    return wrappee(site_context, args, path_config, persisting_function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 499, in _command_update_active
    uninstalled, installed = update_active_packages(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 610, in update_active_packages
    _install_applicable_inactive_packages(
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 669, in _install_applicable_inactive_packages
    install(
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 297, in install
    return _install(
           ^^^^^^^^^
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 347, in _install
    extract_mkp(manifest, mkp, path_config.get_path)
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_mkp.py", line 239, in extract_mkp
    _extract_tgz(
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_mkp.py", line 252, in _extract_tgz
    _extract_tar(tar, tarname, dst, filenames)
  File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_mkp.py", line 265, in _extract_tar
    tarsource = tar.extractfile(name)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/misoft/lib/python3.12/tarfile.py", line 2402, in extractfile
    tarinfo = self.getmember(member)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/misoft/lib/python3.12/tarfile.py", line 2018, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'cmk_addons_plugins.tar' not found"
OMD[misoft]:~$ mkp update-active
[proxmox_bs 0.4.21]: Installing
[proxmox_bs 0.4.21]: Not installed: File conflict: /omd/sites/misoft/local/share/check_mk/agents/plugins/proxmox_bs (already existing)
```

I am not sure what I am doing wrong here, we are using Checkmk Raw Edition 2.3.0p31

**Comment by fdriessler** [comment]
> ```
> root@pbsbn:/usr/lib/check_mk_agent/plugins# chmod +x proxmox_bs.py 
> root@pbsbn:/usr/lib/check_mk_agent/plugins# ls -l
> total 8
> -rwxr-xr-x 1 root root 7791 Apr 28 07:18 proxmox_bs.py
> root@pbsbn:/usr/lib/check_mk_agent/plugins# python3 proxmox_bs.py 
> Traceback (most recent call last):
>   File "/usr/lib/check_mk_agent/plugins/proxmox_bs.py", line 9, in <module>
>     from cmk.agent_based.v2 import (
> ModuleNotFoundError: No module named 'cmk'
> ```

Here you seem to be trying to use the wrong file on the PBS host (Based on the fact its a python file and it has a agent_based import error, its the check plugin for checkmk).
The file that has to be placed on the guest_agent is located in `agents/plugins/proxmox_bs` inside this repository, or within 
`/opt/omd/sites/<site-name>/local/share/check_mk/agents/plugins/proxmox_bs` on the checkmk host, if the mkp is activated.

Additionally, if not already present, a config has to be created on the pbs (`/etc/check_mk/proxmox_bs.env`):
```
export PBS_USERNAME='<user@realm>'
export PBS_PASSWORD='<password of user>'
export PBS_DNS_NAME='<dns-name:port>'
export PBS_FINGERPRINT=''
```


As for the latter issue:
> ```
> [proxmox_bs 0.4.21]: Installing
> Traceback (most recent call last):
>   File "/omd/sites/misoft/bin/mkp", line 83, in <module>
>     cli.main(
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 813, in main
>     args.handler(
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 84, in wrapped
>     return wrappee(site_context, args, path_config, persisting_function)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/cli.py", line 499, in _command_update_active
>     uninstalled, installed = update_active_packages(
>                              ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 610, in update_active_packages
>     _install_applicable_inactive_packages(
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 669, in _install_applicable_inactive_packages
>     install(
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 297, in install
>     return _install(
>            ^^^^^^^^^
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_unsorted.py", line 347, in _install
>     extract_mkp(manifest, mkp, path_config.get_path)
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_mkp.py", line 239, in extract_mkp
>     _extract_tgz(
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_mkp.py", line 252, in _extract_tgz
>     _extract_tar(tar, tarname, dst, filenames)
>   File "/omd/sites/misoft/lib/python3.12/site-packages/cmk/mkp_tool/_mkp.py", line 265, in _extract_tar
>     tarsource = tar.extractfile(name)
>                 ^^^^^^^^^^^^^^^^^^^^^
>   File "/omd/sites/misoft/lib/python3.12/tarfile.py", line 2402, in extractfile
>     tarinfo = self.getmember(member)
>               ^^^^^^^^^^^^^^^^^^^^^^
>   File "/omd/sites/misoft/lib/python3.12/tarfile.py", line 2018, in getmember
>     raise KeyError("filename %r not found" % name)
> KeyError: "filename 'cmk_addons_plugins.tar' not found"                   
> ```

There appears to have been a issue packaging the mkp; the cmk_addons_files path was not included in the mkp. We've created a new release that includes those missing files.

**Comment by peterge-misoft** [comment]
Sorry, I downloaded the wrong file - my bad. Fixed it and placed [this](https://github.com/inettgmbh/checkmk-proxmox_backup_server/blob/main/agents/plugins/proxmox_bs) in `/usr/lib/check_mk_agent/plugins`.

I updated to 0.4.23, and now it looks good on the CMK server:
```
OMD[misoft]:~$ mkp update-active
[proxmox_bs 0.4.23]: Installing
[proxmox_bs 0.4.23]: Installed
OMD[misoft]:~$ mkp list
Name       Version Title                      Author                                                                    Req. Version Until Version Files State                        
---------- ------- -------------------------- ------------------------------------------------------------------------- ------------ ------------- ----- -----------------------------
proxmox_bs 0.4.23  Proxmox Backup Server      Felix Driessler <fdriessler@inett.de>                                     2.3.0b6      None          5     Enabled (active on this site)
redfish    2.3.38  Redfish Restful API Checks Andreas Doehler (andreas.doehler@bechtle.com / andreas.doehler@gmail.com) 2.3.0b6      2.3.99        28    Disabled  
```

But it is still not working properly. CMK shows
![Image](https://github.com/user-attachments/assets/cd98dca1-4adf-4569-9082-9c8a180553a8)
It's not working using [this](https://github.com/inettgmbh/checkmk-proxmox_backup_server/issues/7#issuecomment-1970680874) format, neither with the format you posted, which is in my case:
```
root@pbsbn:/usr/lib/check_mk_agent/plugins# cat /etc/check_mk/proxmox_bs.env 
#!/bin/bash
export PBS_USERNAME='root@pam!checkmk'
export PBS_PASSWORD='freshly_generated_token_secret'
export PBS_REPOSITORY='pbsbn.misoft.lan:8007'
export PBS_FINGERPRINT='6e:04...fingerprint...b9:c8'
```

The ouput looks like this. What am I doing wrong?
```
root@pbsbn:/usr/lib/check_mk_agent/plugins# ./proxmox_bs 
<<<proxmox_bs>>>
===requirements===
0 proxmox-backup-manager
0 proxmox-backup-client
0 jq
===proxmox-backup-manager versions===
/bin/env proxmox-backup-manager versions --output-format json
[{"Arch":"amd64","Description":"Proxmox Backup Server daemon with tools and GUI\n This package contains the Proxmox Backup Server daemons and related\n tools. This includes a web-based graphical user interface.","ExtraInfo":"running version: 3.3.2","OldVersion":"3.3.2-1","Origin":"Proxmox","Package":"proxmox-backup-server","Priority":"optional","Section":"admin","Title":"Proxmox Backup Server daemon with tools and GUI","Version":"3.4.1-1"}]
===proxmox-backup-manager datastore list===
/bin/env proxmox-backup-manager datastore list --output-format json | tee /tmp/tmp.MpiuP91OGq
[{"comment":"","gc-schedule":"12:00","name":"DasiBN","path":"/mnt/pve/DasiBN/proxmox-backup-server"}]
===proxmox-backup-manager task list===
/bin/env proxmox-backup-manager task list --output-format json
[{"node":"localhost","pid":864,"pstart":588,"starttime":1745846375,"upid":"UPID:pbsbn:00000360:0000024C:00000000:680F8067:termproxy::root@pam:","user":"root@pam","worker_id":null,"worker_type":"termproxy"},{"node":"localhost","pid":966,"pstart":599,"starttime":1745845200,"upid":"UPID:pbsbn:000003C6:00000257:000001FF:680F7BD0:verificationjob:DasiBN\\x3av\\x2d63934b51\\x2dced1:root@pam:","user":"root@pam","worker_id":"DasiBN:v-63934b51-ced1","worker_type":"verificationjob"}]
Error: unable to parse repository url 'root@pam!checkmk@:DasiBN'
root@pbsbn:/usr/lib/check_mk_agent/plugins# ./proxmox_bs 
<<<proxmox_bs>>>
===requirements===
0 proxmox-backup-manager
0 proxmox-backup-client
0 jq
===proxmox-backup-manager versions===
/bin/env proxmox-backup-manager versions --output-format json
[{"Arch":"amd64","Description":"Proxmox Backup Server daemon with tools and GUI\n This package contains the Proxmox Backup Server daemons and related\n tools. This includes a web-based graphical user interface.","ExtraInfo":"running version: 3.3.2","OldVersion":"3.3.2-1","Origin":"Proxmox","Package":"proxmox-backup-server","Priority":"optional","Section":"admin","Title":"Proxmox Backup Server daemon with tools and GUI","Version":"3.4.1-1"}]
===proxmox-backup-manager datastore list===
/bin/env proxmox-backup-manager datastore list --output-format json | tee /tmp/tmp.4hUFAJa1HJ
[{"comment":"","gc-schedule":"12:00","name":"DasiBN","path":"/mnt/pve/DasiBN/proxmox-backup-server"}]
===proxmox-backup-manager task list===
/bin/env proxmox-backup-manager task list --output-format json
[{"node":"localhost","pid":864,"pstart":588,"starttime":1745846375,"upid":"UPID:pbsbn:00000360:0000024C:00000000:680F8067:termproxy::root@pam:","user":"root@pam","worker_id":null,"worker_type":"termproxy"},{"node":"localhost","pid":966,"pstart":599,"starttime":1745845200,"upid":"UPID:pbsbn:000003C6:00000257:000001FF:680F7BD0:verificationjob:DasiBN\\x3av\\x2d63934b51\\x2dced1:root@pam:","user":"root@pam","worker_id":"DasiBN:v-63934b51-ced1","worker_type":"verificationjob"}]
Error: unable to parse repository url 'root@pam!checkmk@:DasiBN'
===proxmox-backup-manager garbage-collection status===DasiBN
/bin/env proxmox-backup-manager garbage-collection status DasiBN --output-format json | tee /tmp/tmp.GoFTS8RgjJ
{"disk-bytes":953308212094,"disk-chunks":747262,"duration":11529,"index-data-bytes":48389403721156,"index-file-count":310,"last-run-endtime":1745845929,"last-run-state":"OK","next-run":1745920800,"pending-bytes":35994758064,"pending-chunks":28388,"removed-bad":0,"removed-bytes":34746870127,"removed-chunks":28607,"schedule":"12:00","still-bad":0,"store":"DasiBN","upid":"UPID:pbsbn:000003C6:00000257:000001FE:680F51A0:garbage_collection:DasiBN:root@pam:"}
===proxmox-backup-client list===DasiBN
/bin/env proxmox-backup-client list --repository root@pam!checkmk@:DasiBN --output-format json
Error: parameter verification failed - 'repository': value does not match the regex pattern
Usage: proxmox-backup-client list [OPTIONS]

Optional parameters:

 --ns       <string>
             Namespace.
 --output-format text|json|json-pretty
             Output format.
 --repository <string>
             Repository URL.===proxmox-backup-client snapshot list===DasiBN
/bin/env proxmox-backup-client snapshot list --repository root@pam!checkmk@:DasiBN --output-format json
Error: parameter verification failed - 'repository': value does not match the regex pattern
Usage: proxmox-backup-client snapshot list [<group>] [OPTIONS]

 <group>    <string>
             Backup group.

Optional parameters:

 --ns       <string>
             Namespace.
 --output-format text|json|json-pretty
             Output format.
 --repository <string>
             Repository URL.===proxmox-backup-client status===DasiBN
/bin/env proxmox-backup-client status --repository root@pam!checkmk@:DasiBN --output-format json
Error: parameter verification failed - 'repository': value does not match the regex pattern
Usage: proxmox-backup-client status [OPTIONS]

Optional parameters:

 --output-format text|json|json-pretty
             Output format.
 --repository <string>
             Repository URL.===proxmox-backup-manager task log===UPID:pbsbn:000003C6:00000257:000001FE:680F51A0:garbage_collection:DasiBN:root@pam:
/bin/env proxmox-backup-manager task log UPID:pbsbn:000003C6:00000257:000001FE:680F51A0:garbage_collection:DasiBN:root@pam: 2>&1 | sed '/^Removed /,$!d'
Removed garbage: 32.361 GiB
Removed chunks: 28607
Pending removals: 33.523 GiB (in 28388 chunks)
Original data usage: 44.01 TiB
On-Disk usage: 887.837 GiB (1.97%)
On-Disk chunks: 747262
Deduplication factor: 50.76
Average chunk size: 1.217 MiB
TASK OK
removed '/tmp/tmp.gcQmyO7Gk0'
===EOD===
=
```

**Comment by fdriessler** [comment]
> root@pbsbn:/usr/lib/check_mk_agent/plugins# cat /etc/check_mk/proxmox_bs.env 
> #!/bin/bash
> export PBS_USERNAME='root@pam!checkmk'
> export PBS_PASSWORD='freshly_generated_token_secret'
> export PBS_REPOSITORY='pbsbn.misoft.lan:8007'
> export PBS_FINGERPRINT='6e:04...fingerprint...b9:c8'

The error here is the third line of the `proxmox_bs.env`; The key is supposed to be `PBS_DNS_NAME` rather than `PBS_REPOSITORY`.
If changing the key doesn't work, try changing it to be `export PBS_DNS_NAME='localhost'` (without port), which was the hardcoded goto in the older version. DNS_NAME:PORT should not work, if the pbs cannot resolve the hostname.

**Comment by peterge-misoft** [comment]
Fixes it, thanks a lot @fdriessler !
